### ISSUE TITLE
Erreur dans le fichier TestExecutorLib.py

### ISSUE THREAD

**Issue by Hachebourin** [dmachard/extensive-testing#1]
Il y a une erreur dans la fonction virtualRun du fichier TestExecutorLib.py.
J'ai remplacé la ligne `return _executerun` par  `return not _ExecuteTest` :

```python
def virtualRun(self):
    """
    todo
    """
    return not _ExecuteTest
    #return _executerun -> Erreur 
```

**Comment by dmachard** [comment]
Fix in master and unstable branches
