### ISSUE TITLE
hping3 is not installed

### ISSUE THREAD

**Issue by Hachebourin** [dmachard/extensive-testing#2]
Je suis tombé sur cette erreur en lançant le test utilisant l'adaptateur Pinger :

![hping3](https://user-images.githubusercontent.com/19730082/32374660-fece3ce4-c09e-11e7-99c6-a36e0c48fd20.png)

J'ai téléchargé hping3 ici : [hping3](https://github.com/antirez/hping)

Et pour l'installer sur une rhel7 :
```
cd hping-master
yum install libpcap-devel-1.5.3-9.el7.x86_64
ln -s /usr/include/pcap/bpf.h /usr/include/net/bpf.h
./configure
make
make install
```

**Comment by dmachard** [comment]
J'ai ajouté ce point dans la FAQ [How to fix error hping3 is not installed in test](https://documentations.extensivetesting.org/docs/troubleshooting/faqs#how-to-fix-error-hping3-is-not-installed-in-test)

L'adaptateur Pinger>TCP utilise l'outil hping3
